package workshop.akbolatss.xchangesrates.model.dao;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "CHART_DATA_INFO".
 */
@Entity
public class ChartDataInfo {

    @Id(autoincrement = true)
    private Long id;
    private Float volume;
    private String high;
    private Float change24;
    private String last;
    private String low;
    private String buy;
    private String sell;
    private Float change;
    private String started;
    private String multiply;
    private String updated;
    private Long timestamp;
    private Long infoId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ChartDataInfo() {
    }

    public ChartDataInfo(Long id) {
        this.id = id;
    }

    @Generated
    public ChartDataInfo(Long id, Float volume, String high, Float change24, String last, String low, String buy, String sell, Float change, String started, String multiply, String updated, Long timestamp, Long infoId) {
        this.id = id;
        this.volume = volume;
        this.high = high;
        this.change24 = change24;
        this.last = last;
        this.low = low;
        this.buy = buy;
        this.sell = sell;
        this.change = change;
        this.started = started;
        this.multiply = multiply;
        this.updated = updated;
        this.timestamp = timestamp;
        this.infoId = infoId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Float getVolume() {
        return volume;
    }

    public void setVolume(Float volume) {
        this.volume = volume;
    }

    public String getHigh() {
        return high;
    }

    public void setHigh(String high) {
        this.high = high;
    }

    public Float getChange24() {
        return change24;
    }

    public void setChange24(Float change24) {
        this.change24 = change24;
    }

    public String getLast() {
        return last;
    }

    public void setLast(String last) {
        this.last = last;
    }

    public String getLow() {
        return low;
    }

    public void setLow(String low) {
        this.low = low;
    }

    public String getBuy() {
        return buy;
    }

    public void setBuy(String buy) {
        this.buy = buy;
    }

    public String getSell() {
        return sell;
    }

    public void setSell(String sell) {
        this.sell = sell;
    }

    public Float getChange() {
        return change;
    }

    public void setChange(Float change) {
        this.change = change;
    }

    public String getStarted() {
        return started;
    }

    public void setStarted(String started) {
        this.started = started;
    }

    public String getMultiply() {
        return multiply;
    }

    public void setMultiply(String multiply) {
        this.multiply = multiply;
    }

    public String getUpdated() {
        return updated;
    }

    public void setUpdated(String updated) {
        this.updated = updated;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public Long getInfoId() {
        return infoId;
    }

    public void setInfoId(Long infoId) {
        this.infoId = infoId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
