package workshop.akbolatss.xchangesrates.model.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SNAPSHOT".
*/
public class SnapshotDao extends AbstractDao<Snapshot, Long> {

    public static final String TABLENAME = "SNAPSHOT";

    /**
     * Properties of entity Snapshot.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Exchange = new Property(1, String.class, "exchange", false, "EXCHANGE");
        public final static Property Coin = new Property(2, String.class, "coin", false, "COIN");
        public final static Property Currency = new Property(3, String.class, "currency", false, "CURRENCY");
        public final static Property Source = new Property(4, String.class, "source", false, "SOURCE");
        public final static Property IsActiveForGlobal = new Property(5, Boolean.class, "isActiveForGlobal", false, "IS_ACTIVE_FOR_GLOBAL");
        public final static Property Timing = new Property(6, String.class, "timing", false, "TIMING");
        public final static Property IsIntervalEnabled = new Property(7, Boolean.class, "isIntervalEnabled", false, "IS_INTERVAL_ENABLED");
        public final static Property IntervalNumber = new Property(8, Integer.class, "IntervalNumber", false, "INTERVAL_NUMBER");
        public final static Property IntervalType = new Property(9, Integer.class, "IntervalType", false, "INTERVAL_TYPE");
        public final static Property IsNotifyPersistent = new Property(10, Boolean.class, "isNotifyPersistent", false, "IS_NOTIFY_PERSISTENT");
        public final static Property InfoId = new Property(11, long.class, "infoId", false, "INFO_ID");
    }

    private DaoSession daoSession;


    public SnapshotDao(DaoConfig config) {
        super(config);
    }
    
    public SnapshotDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SNAPSHOT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"EXCHANGE\" TEXT," + // 1: exchange
                "\"COIN\" TEXT," + // 2: coin
                "\"CURRENCY\" TEXT," + // 3: currency
                "\"SOURCE\" TEXT," + // 4: source
                "\"IS_ACTIVE_FOR_GLOBAL\" INTEGER," + // 5: isActiveForGlobal
                "\"TIMING\" TEXT," + // 6: timing
                "\"IS_INTERVAL_ENABLED\" INTEGER," + // 7: isIntervalEnabled
                "\"INTERVAL_NUMBER\" INTEGER," + // 8: IntervalNumber
                "\"INTERVAL_TYPE\" INTEGER," + // 9: IntervalType
                "\"IS_NOTIFY_PERSISTENT\" INTEGER," + // 10: isNotifyPersistent
                "\"INFO_ID\" INTEGER NOT NULL );"); // 11: infoId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SNAPSHOT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Snapshot entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String exchange = entity.getExchange();
        if (exchange != null) {
            stmt.bindString(2, exchange);
        }
 
        String coin = entity.getCoin();
        if (coin != null) {
            stmt.bindString(3, coin);
        }
 
        String currency = entity.getCurrency();
        if (currency != null) {
            stmt.bindString(4, currency);
        }
 
        String source = entity.getSource();
        if (source != null) {
            stmt.bindString(5, source);
        }
 
        Boolean isActiveForGlobal = entity.getIsActiveForGlobal();
        if (isActiveForGlobal != null) {
            stmt.bindLong(6, isActiveForGlobal ? 1L: 0L);
        }
 
        String timing = entity.getTiming();
        if (timing != null) {
            stmt.bindString(7, timing);
        }
 
        Boolean isIntervalEnabled = entity.getIsIntervalEnabled();
        if (isIntervalEnabled != null) {
            stmt.bindLong(8, isIntervalEnabled ? 1L: 0L);
        }
 
        Integer IntervalNumber = entity.getIntervalNumber();
        if (IntervalNumber != null) {
            stmt.bindLong(9, IntervalNumber);
        }
 
        Integer IntervalType = entity.getIntervalType();
        if (IntervalType != null) {
            stmt.bindLong(10, IntervalType);
        }
 
        Boolean isNotifyPersistent = entity.getIsNotifyPersistent();
        if (isNotifyPersistent != null) {
            stmt.bindLong(11, isNotifyPersistent ? 1L: 0L);
        }
        stmt.bindLong(12, entity.getInfoId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Snapshot entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String exchange = entity.getExchange();
        if (exchange != null) {
            stmt.bindString(2, exchange);
        }
 
        String coin = entity.getCoin();
        if (coin != null) {
            stmt.bindString(3, coin);
        }
 
        String currency = entity.getCurrency();
        if (currency != null) {
            stmt.bindString(4, currency);
        }
 
        String source = entity.getSource();
        if (source != null) {
            stmt.bindString(5, source);
        }
 
        Boolean isActiveForGlobal = entity.getIsActiveForGlobal();
        if (isActiveForGlobal != null) {
            stmt.bindLong(6, isActiveForGlobal ? 1L: 0L);
        }
 
        String timing = entity.getTiming();
        if (timing != null) {
            stmt.bindString(7, timing);
        }
 
        Boolean isIntervalEnabled = entity.getIsIntervalEnabled();
        if (isIntervalEnabled != null) {
            stmt.bindLong(8, isIntervalEnabled ? 1L: 0L);
        }
 
        Integer IntervalNumber = entity.getIntervalNumber();
        if (IntervalNumber != null) {
            stmt.bindLong(9, IntervalNumber);
        }
 
        Integer IntervalType = entity.getIntervalType();
        if (IntervalType != null) {
            stmt.bindLong(10, IntervalType);
        }
 
        Boolean isNotifyPersistent = entity.getIsNotifyPersistent();
        if (isNotifyPersistent != null) {
            stmt.bindLong(11, isNotifyPersistent ? 1L: 0L);
        }
        stmt.bindLong(12, entity.getInfoId());
    }

    @Override
    protected final void attachEntity(Snapshot entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Snapshot readEntity(Cursor cursor, int offset) {
        Snapshot entity = new Snapshot( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // exchange
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // coin
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // currency
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // source
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // isActiveForGlobal
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // timing
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0, // isIntervalEnabled
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // IntervalNumber
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // IntervalType
            cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0, // isNotifyPersistent
            cursor.getLong(offset + 11) // infoId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Snapshot entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setExchange(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCoin(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCurrency(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSource(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIsActiveForGlobal(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setTiming(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setIsIntervalEnabled(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
        entity.setIntervalNumber(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setIntervalType(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setIsNotifyPersistent(cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0);
        entity.setInfoId(cursor.getLong(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Snapshot entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Snapshot entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Snapshot entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSnapshotInfoDao().getAllColumns());
            builder.append(" FROM SNAPSHOT T");
            builder.append(" LEFT JOIN SNAPSHOT_INFO T0 ON T.\"INFO_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Snapshot loadCurrentDeep(Cursor cursor, boolean lock) {
        Snapshot entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        SnapshotInfo info = loadCurrentOther(daoSession.getSnapshotInfoDao(), cursor, offset);
         if(info != null) {
            entity.setInfo(info);
        }

        return entity;    
    }

    public Snapshot loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Snapshot> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Snapshot> list = new ArrayList<Snapshot>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Snapshot> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Snapshot> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
