package workshop.akbolatss.xchangesrates.model.dao;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "SNAPSHOT_CHART".
 */
@Entity
public class SnapshotChart {

    @Id(autoincrement = true)
    private Long id;
    private Float market;
    private String high;
    private String low;
    private String price;
    private Long timestamp;
    private long snapshotId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 1654824671)
    public SnapshotChart() {
    }

    public SnapshotChart(Long id) {
        this.id = id;
    }

    @Generated(hash = 2028579848)
    public SnapshotChart(Long id, Float market, String high, String low, String price, Long timestamp, long snapshotId) {
        this.id = id;
        this.market = market;
        this.high = high;
        this.low = low;
        this.price = price;
        this.timestamp = timestamp;
        this.snapshotId = snapshotId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Float getMarket() {
        return market;
    }

    public void setMarket(Float market) {
        this.market = market;
    }

    public String getHigh() {
        return high;
    }

    public void setHigh(String high) {
        this.high = high;
    }

    public String getLow() {
        return low;
    }

    public void setLow(String low) {
        this.low = low;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public long getSnapshotId() {
        return snapshotId;
    }

    public void setSnapshotId(long snapshotId) {
        this.snapshotId = snapshotId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
